src/food_management/food_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include("user.urls", namespace = "user")),
    path('',include("web.urls", namespace = "web")),
    path('',include("planner.urls", namespace = "planner")),
]



if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) 


    )

src/food_management/planner/urls.py
from django.urls import path
from planner import views

app_name = "planner"

urlpatterns = [
    path('planner/',views.planner, name = "planner"),
    path('edit_order/',views.edit_order, name = "edit_order"),
    path('my_orders/',views.my_orders, name = "my_orders"),
    # path('sample/',views.sample, name = "sample"),
    path('delete/<int:id>/',views.delete_order, name = "delete_order"),
    path('edit/<int:id>/',views.edit_order, name = "edit_order"),

]

src/food_management/user/urls.py
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path('login/',views.login, name = "login"),
    path('logout/',views.logout, name = "logout"),
    path('signup/',views.signup, name = "signup"),
    path('view_profile/',views.view_profile, name = "view_profile"),
    path('edit/',views.edit, name = "edit"),
    # path('student_details/',views.student_details, name = "student_details"),
]

src/food_management/web/urls.py
from django.urls import path
from web import views

app_name = "web"

urlpatterns = [
    path('',views.index, name = "index"),
]

src/food_management/templates/web/includes/header.html
{% load static %}
<header>
    <section class="left">
        <h1><a href="{% url 'web:index' %}"><span>Meal</span> Planner</a></h1>
    </section>
    <section class="right">
        {% if request.user.is_authenticated %}
        <a href="" class=" navbar"><img src="{% static 'images/icons/nav.png' %}" alt=""></a>
        {% else %}
        <a href="{% url 'user:login' %}" class="button">Logo In</a>
        {% endif %}
    </section>
    <div class="navcontainer">
        <div class="hide"></div>
        <div class="nav">
            <div class="top">
                <div class="close">
                    <span class="close">
                        <img src="{% static 'images/icons/close.png' %}" alt="close button">
                    </span>  
                </div>
                <div class="log">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'user:logout' %}" class="button">Logout</a>
                    {% else %}
                    <a href="{% url 'user:login' %}" class="button">LogoIn</a>
                    {% endif %}
                </div>
            </div>
            <div class="profile">
                <span class="image">

                    {% if request.user.student.profile_image %}
                        <img src="{{request.user.student.profile_image.url}}" alt="">
                    {% else %}
                        <img src="{% static 'images/icons/profile.jpg' %}" style="background-color: #fff;" alt="">
                    {% endif %}

                </span>
                <h1>
                    {{request.user.student.name}} 
                </h1>

                {% if request.user.student.mob_number %}
                    <h1>
                        {{request.user.student.mob_number}}
                    </h1>
                {% endif %}

                <a href="{% url 'user:view_profile' %}" class="button">view profile</a>
            </div>
            <div class="list">
                <a href="{% url 'planner:my_orders' %}" class="button"><span>My orders</span> <img src="{% static 'images/icons/scroldown.png' %}" alt=""></a>
                <a href="{% url 'planner:planner' %}" class="button"><span>Create Order</span> <img src="{% static 'images/icons/scroldown.png' %}" alt=""></a>
            </div>
        </div>
    </div>
</header>