src/food_management/food_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include("user.urls", namespace = "user")),
    path('',include("web.urls", namespace = "web")),
    path('',include("planner.urls", namespace = "planner")),
]



if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) 


    )

src/food_management/planner/urls.py
from django.urls import path
from planner import views

app_name = "planner"

urlpatterns = [
    path('planner/',views.planner, name = "planner"),
    path('edit_order/',views.edit_order, name = "edit_order"),
    path('my_orders/',views.my_orders, name = "my_orders"),
    # path('sample/',views.sample, name = "sample"),
    path('delete/<int:id>/',views.delete_order, name = "delete_order"),
    path('edit/<int:id>/',views.edit_order, name = "edit_order"),

]

src/food_management/user/urls.py
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path('login/',views.login, name = "login"),
    path('logout/',views.logout, name = "logout"),
    path('signup/',views.signup, name = "signup"),
    path('view_profile/',views.view_profile, name = "view_profile"),
    path('edit/',views.edit, name = "edit"),
    # path('student_details/',views.student_details, name = "student_details"),
]

src/food_management/web/urls.py
from django.urls import path
from web import views

app_name = "web"

urlpatterns = [
    path('',views.index, name = "index"),
]

src/food_management/user/forms.py
from django import forms
from django.contrib.auth.models import User
from planner.models import Student


class StudentForm(forms.ModelForm):
    class Meta :
        model = User
        fields = ["username","password","email","first_name","last_name",]
        widgets = {
            "password" : forms.widgets.PasswordInput(attrs={"placeholder" : "enter password"}),
             "username" : forms.widgets.TextInput(attrs = {"placeholder" : "enter username"}),
             "first_name" : forms.widgets.TextInput(attrs = {"placeholder" : "enter firstname","required" : "required"}),
             "last_name" : forms.widgets.TextInput(attrs = {"placeholder" : "enter lastname","required" : "required"}),
             "email" : forms.widgets.EmailInput(attrs = {"placeholder" : "enter email","required" : "required"}),
        }
        error_messages= {

            'first_name' : {
                "required" : "enter first name"
                },
            'last_name' : {
                    "required" : "enter last name"
                    },
            'email' : {
                    "required" : "select a email"
                    },
        }
        


class UserForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ["profile_image","student_id","mob_number",]
        widgets = {
            "student_id" : forms.widgets.TextInput(attrs={"required" : "required"}),
             "mob_number" : forms.widgets.TextInput(attrs = {"required" : "required"}),
        }
        error_messages= {
                'student_id' : {
                        "required" : "enter student-id"
                        },
                'mob_number' : {
                        "required" : "enter mob-number"
                        },
        }
        
       

src/food_management/user/views.py
import json

from django.shortcuts import render,reverse
from django.http.response import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login as auth_login , logout as auth_logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


from planner.models import Student, Order
from main.functions import generate_form_errors
from user.forms import StudentForm,UserForm

def login(request):
   if request.method == "POST":
      username = request.POST.get("username")
      password = request.POST.get("password")      

      if username and password :
         user = authenticate(request, username = username, password = password )
         if user is not None :
            auth_login(request, user)
            return(HttpResponseRedirect("/"))
         
         context = {
                "title" : "student Login",
                "error" : True,
                "message" : "Invalid Credentials"
                
         }
         return  render(request, "users/login.html", context = context)
   else:
            context = {
                "title" : "sign in | Meal Planner "

            }
            return render (request, "users/login.html",context = context)
   

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse("user:login"))


def signup(request):
   if request.method == "POST" :
        form = StudentForm(request.POST)
        if form.is_valid():
           instance = form.save(commit=False)
           user = User.objects.create_user(
              username = instance.username,
              password = instance.password,
              first_name = instance.first_name,
              last_name = instance.last_name,
              email = instance.email,
           )
           Student.objects.create(name = instance.first_name +" "+instance.last_name, user=user)
           user = authenticate(request,username=instance.username, password=instance.password)
           auth_login(request, user)
           return HttpResponseRedirect(reverse("user:login"))
        else:
           message = generate_form_errors(form)
           context = {
                "title" : "student signup",
                "error" : True,
                "message" : message,
                "form" : form
            }
           return render(request, "users/signup.html",context = context)
   else:
      
    form = StudentForm()
    context = {
        "title" : "student Signup",
        "form" : form,
    }
    return render (request,"users/signup.html", context = context) 


@login_required(login_url="/user/login/")
def view_profile(request) :
    user = request.user
    student = user.student

    if request.method == "POST":
        mob_number = request.POST.get('mob_number')
        student_id = request.POST.get('student_id')

        if mob_number:
            student.mob_number = mob_number
        if student_id:
            student.student_id = student_id

        if request.FILES.get('profile_image'):
            student.profile_image = request.FILES['profile_image']
        student.save()
        response_data = {
                "message" :"sucessfully profile_updated",
                "title" :"profile updated",
                "status" : "success",
                "redirect_url" : "/",
                "redirect" : "yes"
            }
        return HttpResponse(json.dumps(response_data),content_type = "application/javascript")  
    context = {
            "title": "My Profile",
            "student": student,
    }
    return render(request, "users/view_profile.html", context=context)


def edit(request):
    user = request.user
    student = user.student 

    if request.method == "POST":
        userform = UserForm(request.POST,request.FILES, instance=student)
        if userform.is_valid():
            instance = userform.save(commit=False)
            instance.save()
            response_data = {
                "message" :"sucessfully submitted",
                "title" :"sucessfully submitted",
                "status" : "success",
                "redirect_url" : "/",
                "redirect" : "yes"
            }
            return HttpResponse(json.dumps(response_data),content_type = "application/javascript")
        else:
            response_data = {
                "message" : "something error",
                "title" :"please check",
                "status" : "error",
                "stable" : "yes"

            }
            return HttpResponse(json.dumps(response_data),content_type = "application/javascript")
    else:
        userform = UserForm(instance=student)

    context = {
        "title": "Edit Profile",
        "userform": userform,
    }
    return render (request, "users/edit.html",context=context)

src/food_management/templates/users/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'images/icons/favicon.png' %}" type="image/x-icon">
    <title>{{title}}</title>
</head>
<body>
    {% include "web/includes/header.html" %}
    <section id="profile">
        <section class="data">
            <section class="selection">
                <div class="title">
                    <a href="#" class="button profile"><span>Update Profile</span> <img src="{% static 'images/icons/scroldown.png' %}" alt=""></a>
                </div>
                <div class="reroute">
                    <a href="{% url 'user:view_profile' %}" class="button"><span>My Profile</span> <img src="{% static 'images/icons/scroldown.png' %}" alt=""></a>
                    <a href="{% url 'planner:my_orders' %}" class="button"><span>My orders</span> <img src="{% static 'images/icons/scroldown.png' %}" alt=""></a>
                    <a href="{% url 'planner:planner' %}" class="button"><span>Create Order</span> <img src="{% static 'images/icons/scroldown.png' %}" alt=""></a>
                </div>
            </section>
            <section class="user_data">
                <form action="" method="post" class="ajax redirect" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="container">
                        <div class="input_image">

                            {% if request.user.student.profile_image %}
                                <img src="{{request.user.student.profile_image.url}}" alt="profile image">
                                {{ userform.profile_image.label }}
                                {{ userform.profile_image }}
                            {% else %}
                                <label for="{{ userform.profile_image.id_for_label }}">{{ userform.profile_image.label }}</label>
                                {{ userform.profile_image }}
                            {% endif %}
                       
                        </div>
                        <div class="input_cont">
                            <label for="{{ userform.mob_number.id_for_label }}">{{ userform.mob_number.label_tag }}</label>
                            {{ userform.mob_number }}
                        </div>
                        <div class="input_cont">
                            <label for="{{ userform.student_id.id_for_label }}">{{ userform.student_id.label_tag }}</label>
                            {{ userform.student_id }}
                        </div>   
                        <div class="submit_container">    
                            <button type="submit">submit</button>
                        </div>     
                    </div>  
                </form>
            </section>
        </section>
</section>
    <script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

src/food_management/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'images/icons/favicon.png' %}" type="image/x-icon">
    <title>{{title}}</title>
</head>
<body>
    <section id="login">
        <section class="title">
            <span>welcome to <h1> Meal</h1> planner</span>
            <h3>select your favourite meals</h3>
        </section>
        <section class="form">
            <div class="top">
                <h1>Student Login</h1>
            </div>
            <div class="bottom">
                <form action="" method="post">
                {% csrf_token %}

                    <div class="input_container">
                        <label for="id_username">Username</label>
                        <input id="id_username" name="username" type="text" placeholder="Enter Username" >
                    </div>
                    <div class="input_container">
                        <label for="id_password">Password</label>
                        <input id="id_password" name="password" type="password" placeholder="Enter password">
                    </div>
                    <div class="submit_container">
                        {% if error %}
                        <p class="error_message">{{message}}</p>
                        {% endif %}
                        <button type="submit">Log in</button>
                    </div>
                </form>
                <span>Not Registered ?</span>
                <a href="{% url 'user:signup' %}">Signup</a>
            </div>
        </section>
    </section>
</body>
</html>

src/food_management/templates/users/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{{title}}</title>
</head>
<body>
    <section id="login">
        <section class="title">
            <span>welcome to <h1> Meal</h1> planner</span>
            <h3>select your favourite meals</h3>
        </section>
        <section class="form">
            <div class="top">
                <h1>Create Account</h1>
            </div>
            <div class="bottom">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="top">
                        <div class="right">
                            {% for field in form %}

                                <div class="input_container">
                                    <label for="field.id_for_label">{{field.label}}</label>
                                    {{field}}
                                </div>

                            {% endfor %}
                        </div>
                        <div class="submit_container">
                            {% if error %}
                            <p class="error_message">{{message}}</p>
                            {% endif %}
                            <button class="submit" type="submit">Create</button>
                        </div>
                    </div>
                </form>
                <span>already have an acount ?</span>
                <a href="{% url 'user:login' %}">Login</a>
            </div>
        </section>
    </section>
</body>
</html>

src/food_management/templates/users/view_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'images/icons/favicon.png' %}" type="image/x-icon">
    <title>{{title}}</title>
</head>
<body>
    {% include "web/includes/header.html" %}
    <section id="profile">
            <section class="data">
                <section class="selection">
                    <div class="title">
                        <a href="#" class="button profile"><span>Profile</span> <img src="{% static 'images/icons/scroldown.png' %}" alt=""></a>
                    </div>
                    <div class="reroute">
                        <a href="{% url 'planner:my_orders' %}" class="button"><span>My orders</span> <img src="{% static 'images/icons/scroldown.png' %}" alt=""></a>
                        <a href="{% url 'planner:planner' %}" class="button"><span>Create Order</span> <img src="{% static 'images/icons/scroldown.png' %}" alt=""></a>
                    </div>
                </section>
                <section class="user_data">
                    <form action="" method="post" class="ajax redirect " enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="container">
                            <div class="image_default">

                                {% if not request.user.student.profile_image %}
                                    <div class="image_container">
                                        <img src="{% static 'images/icons/profile.jpg' %}" style="background-color: #fff;" alt="">
                                    </div>
                                    <div class="input_images">
                                        <label for="profile_image">Upload photo : </label>
                                        <input type="file" name="profile_image" accept="image/*">
                                    </div>
                                {% else %}
                                    <div class="image_container">
                                        <img src="{{ request.user.student.profile_image.url }}" alt="Student Image">
                                    </div>
                                    <div class="input_container" >
                                        <span class="edit"><a href="{% url 'user:edit' %}">Change Profile Image 
                                            <img  src="{% static 'images/icons/pencil.svg' %}" alt="profile_image_edit" title="edit.!"></a></span>
                                    </div>
                                {% endif %}

                            </div>
                            <div class="details">
                                <h4>First Name : {{request.user.first_name}}</h4>
                                <h4>Last Name : {{request.user.last_name}}</h4>
                                <h4>Email : {{request.user.email}}</h4>
                            </div>
                            <div class="input">

                                {% if  not request.user.student.mob_number %}
                                    <div class="edit">
                                        <label for="mob_number">Mob Number</label>
                                        <input required type="tel" minlength="10" maxlength="12" name="mob_number" value="">
                                    </div> 
                                {% else %}
                                    <h4>Mobile Number : {{request.user.student.mob_number}}</h4>
                                    <span class="edit"><a href="{% url 'user:edit' %}"><img src="{% static 'images/icons/pencil.svg' %}" alt="edit_number" title="edit.!"></a></span>
                                {% endif%}

                            </div>
                            <div class="input">

                                {% if  not request.user.student.student_id %}
                                    <div class="edit">
                                        <label for="student_id">Student ID</label>
                                        <input  required type="text" name="student_id" value="">
                                    </div>    
                                {% else %}
                                    <h4> Student-ID : {{request.user.student.student_id}}</h4>
                                    <span class="edit"><a href="{% url 'user:edit' %}"><img title="edit.!" src="{% static 'images/icons/pencil.svg' %}" alt="edit_student_id"></a></span>
                                {% endif%}

                            </div>      
                            <div class="submit_container">

                                {% if not request.user.student.mob_number or notrequest.user.student.student_id or  not request.user.student.profile_image %}
                                    <button type="submit">submit</button>
                                {% endif %}

                            </div>               
                        </div>
                    </form>
                </section>
            </section>
    </section>
   
    <script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>