src/food_management/food_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include("user.urls", namespace = "user")),
    path('',include("web.urls", namespace = "web")),
    path('',include("planner.urls", namespace = "planner")),
]



if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) 


    )

src/food_management/planner/urls.py
from django.urls import path
from planner import views

app_name = "planner"

urlpatterns = [
    path('planner/',views.planner, name = "planner"),
    path('edit_order/',views.edit_order, name = "edit_order"),
    path('my_orders/',views.my_orders, name = "my_orders"),
    # path('sample/',views.sample, name = "sample"),
    path('delete/<int:id>/',views.delete_order, name = "delete_order"),
    path('edit/<int:id>/',views.edit_order, name = "edit_order"),

]

src/food_management/web/urls.py
from django.urls import path
from web import views

app_name = "web"

urlpatterns = [
    path('',views.index, name = "index"),
]

src/food_management/planner/models.py
from django.db import models


FOOD_TYPE = (
    ("breakfast", "Breakfast") ,
    ("lunch", "Lunch") ,
    ("snack", "Snack") ,
    ("dinner", "Dinner") ,
)

class Student(models.Model):
    name = models.CharField(max_length=100)
    profile_image = models.ImageField(upload_to= "Student/profile/", blank=True,null=True)
    mob_number = models.CharField(max_length=15,null=True,blank=True)
    student_id = models.CharField(max_length=15,null=True,blank=True)
    user = models.OneToOneField("auth.User",on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Meal(models.Model):
    food_image = models.ImageField(upload_to="breakfast/", null=True,blank=True)
    dish_name = models.CharField(max_length=200)
    food_type = models.CharField(max_length=128,choices=FOOD_TYPE)
    meal_date = models.DateField()
    is_draft = models.BooleanField(default=False)


    def __str__(self):
        return self.dish_name
    

class Order (models.Model):
    selected_date = models.DateField()
    selected_breakfast = models.CharField(max_length=200)
    selected_lunch = models.CharField(max_length=200)
    selected_snack = models.CharField(max_length=200)
    selected_dinner = models.CharField(max_length=200)

    
    student = models.ForeignKey("planner.Student", on_delete=models.CASCADE)
    is_draft = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.selected_breakfast 

src/food_management/planner/forms.py
from django import forms
from django.forms import ModelForm
from planner.models import Order

class OrderForm(ModelForm):

    class Meta : 
        model = Order
        exclude = ["student","is_draft","is_deleted",]
        widgets = {

            "selected_breakfast" : forms.TextInput(attrs ={
                "readonly":"readonly",
                "id":"selected_input_breakfast"
                }),
             "selected_lunch" : forms.TextInput(attrs ={
                "readonly":"readonly",
                "id":"selected_input_lunch"
                }),
             "selected_snack" : forms.TextInput(attrs ={
                "readonly":"readonly",
                "id":"selected_input_snack"
                }),
             "selected_dinner" : forms.TextInput(attrs ={
                "readonly":"readonly",
                "id":"selected_input_dinner"
                }),
        }
        error_messages= {
            'selected_date' : {
                "required" : "select a date"
                },

            'selected_breakfast' : {
                "required" : "select a breakfast"
                },
            'selected_lunch' : {
                    "required" : "select a lunch"
                    },
            'selected_snack' : {
                    "required" : "select a snack"
                    },
            'selected_dinner' : {
                    "required" : "select a dinner"
                    },
        }


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['selected_date'].widget = forms.DateInput(attrs={ 
            "id":"selected_input_date",
            "readonly":"readonly",
        })

src/food_management/planner/views.py
import datetime 
import json

from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,get_object_or_404

from main.decorators import allow_self
from main.functions import generate_form_errors
from planner.models import Student
from planner.forms import OrderForm
from planner.models import Meal, Order

@login_required(login_url = "/user/login/")
def planner (request):

    breakfast = Meal.objects.filter(food_type = "breakfast")
    lunch = Meal.objects.filter(food_type = "lunch")
    snack = Meal.objects.filter(food_type = "snack")
    dinner = Meal.objects.filter(food_type = "dinner")

    today = datetime.date.today()
    start_date =today
    next_7_days = [today + datetime.timedelta(days=i) for i in range(7)]
    
    queryset = Order.objects.filter(student__user = request.user,is_deleted=False).values_list("selected_date", flat=True,)
    # selected_date = [date.strftime('%b, %d, %Y') for date in queryset]
    selected_date = list(queryset)

    print(next_7_days)
    print(selected_date)
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            student = request.user.student
            
            instances = form.save(commit=False) 
            instances.student = student
            instances.save()

            response_data = {
                "message" :"sucessfully submitted",
                "title" :"sucessfully submitted",
                "status" : "success",
                "redirect_url" : "/",
                "redirect" : "yes"
            }

            return HttpResponse(json.dumps(response_data),content_type = "application/javascript")
        else:
            error_message = generate_form_errors(form)

            response_data = {
                    "message" :str(error_message),
                    "title" :"please check something error occured",
                    "status" : "error",
                    "redirect_url" : "/",
                    "redirect" : "yes"
                }

            return HttpResponse(json.dumps(response_data),content_type = "application/javascript")
    
    else: 
        # data = {
        #     "selected_date" : "2023-07-03",
        #     "selected_breakfast" : "idli",
        #     "selected_lunch" : "meals",
        #     "selected_snack" : "vada",
        #     "selected_dinner" : "chicken curry",

        # }
        form = OrderForm()
           
    context ={
        "form" : form,
        "start_date" : start_date,
        "today" : today,
        "next_7_days": next_7_days,
        "breakfast" : breakfast,
        "lunch" : lunch,
        "snack" : snack,
        "dinner" : dinner,
        "selected_date" : selected_date,
        "title" : "make your order here"

        }

    return render (request, "planner/planner.html", context = context)

@login_required(login_url = "/user/login/")
def my_orders(request):
    order = Order.objects.filter(student__user = request.user,is_deleted = False )
    today = datetime.date.today()
    queryset = Order.objects.filter(student__user = request.user,is_deleted=False).values_list("selected_date", flat=True)
    # selected_date = [date.strftime('%b. %d, %Y') for date in queryset]
    list_date = list(queryset)
    required_date = [d for d in list_date if d >= today]

    print(required_date )


    context = {
        "title" : "My Orders",
        "order" : order,
        "today" : today,
        "required_date" : required_date

    }
    return render(request,"planner/my_orders.html",context = context )


@login_required(login_url = "/user/login/")
@allow_self
def delete_order(request,id):
    instance = get_object_or_404(Order,id=id)
    instance.is_deleted = True
    instance.save()
    
    request_data = {
        "title" : "successfully deleted",
        "message" : "Order deleted successfully",
        "status" : "success",
    }
    return HttpResponse(json.dumps(request_data),content_type = "application/json")



@login_required(login_url="/user/login/")
@allow_self
def edit_order(request,id):
    instance = get_object_or_404(Order,id=id)
    breakfast = Meal.objects.filter(food_type = "breakfast")
    lunch = Meal.objects.filter(food_type = "lunch")
    snack = Meal.objects.filter(food_type = "snack")
    dinner = Meal.objects.filter(food_type = "dinner")

    today = datetime.date.today()
    start_date =today
    next_7_days = [today + datetime.timedelta(days=i) for i in range(7)]
    
    queryset = Order.objects.filter(is_deleted=False).values_list("selected_date", flat=True,)
    # selected_date = [date.strftime('%b. %d, %Y') for date in queryset]
    selected_date = list(queryset)

    print(next_7_days)
    if request.method == 'POST':
        form = OrderForm(request.POST,instance = instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            
            response_data = {
                "message" :"sucessfully submitted",
                "title" :"sucessfully submitted",
                "status" : "success",
                "redirect_url" : "/",
                "redirect" : "yes"
            }
            return HttpResponse(json.dumps(response_data),content_type = "application/javascript")
        else:
            error_message = generate_form_errors(form)
            response_data = {
                "message" :str(error_message),
                "title" :"please check",
                "status" : "error",
                "stable" : "yes"

            }
            return HttpResponse(json.dumps(response_data),content_type = "application/javascript")  
        
    else:
        
        form = OrderForm(instance = instance)
        context = {
                "title" : "Edit order",
                "form" : form,
                "start_date" : start_date,
                "today" : today,
                "next_7_days": next_7_days,
                "breakfast" : breakfast,
                "lunch" : lunch,
                "snack" : snack,
                "dinner" : dinner,
                "selected_date" : selected_date

        }

        return render (request, "planner/edit_order.html",context = context)

src/food_management/templates/planner/edit_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'images/icons/favicon.png' %}" type="image/x-icon">
    <title>{{title}}</title>
</head>
<body>
    {% include "web/includes/header.html" %}
    <section id="edit">
        <section class="wrapper">
                <div class="top">
                    <div class="for_hide">
                        <input type="hidden" name="selected_date" id="selected_date_input">
                        <input type="hidden" name="selected_bf" id="selected_bf_input">
                        <input type="hidden" name="selected_lc" id="selected_lc_input">
                        <input type="hidden" name="selected_snacks" id="selected_sk_input">
                        <input type="hidden" name="selected_dr" id="selected_dr_input">
                    </div>  
                </div>
                <div class="meals">   
                        <div class="item">
                            <div class="menu_head">
                                <h3>Breakfast</h3>
                            </div>
                            <div class="menu breakfast">
                                <ul>
                                    {% for meal in breakfast %}
                                        <li class="item">
                                            <span class="radio">
                                                <span class="label"></span>
                                            </span>
                                            <a href="#" data-value="{{ meal.dish_name }}" >{{ meal.dish_name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="item">
                            <div class="menu_head">
                                <h3>Lunch</h3>
                            </div>
                            <div class="menu lunch">
                                <ul>
                                    {% for meal in lunch %}
                                        <li class="item">
                                            <span class="radio">
                                                <span class="label"></span>
                                            </span>
                                            <a href="#" data-value="{{ meal.dish_name }}" >{{ meal.dish_name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="item">
                            <div class="menu_head">
                                <h3>Evening Snack</h3>
                            </div>
                            <div class="menu snack" >
                                <ul>
                                    {% for meal in snack %}
                                        <li class="item">
                                            <span class="radio">
                                                <span class="label"></span>
                                            </span>
                                            <a href="#" data-value="{{ meal.dish_name }}" >{{ meal.dish_name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>      
                        </div>
                        <div class="item">
                            <div class="menu_head">
                                <h3>Dinner</h3>
                            </div>
                            <div class="menu dinner">
                                <ul>
                                    {% for meal in dinner %}
                                        <li class="item">
                                            <span class="radio">
                                                <span class="label"></span>
                                            </span>
                                            <a href="#" data-value="{{ meal.dish_name }}" >{{ meal.dish_name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>     
                        </div>
                        <div class="ready">
                            <button href="" class="button">make Selection</button>
                            <p class="info">click make selection and scroll down to confirm your order..!</p>
                        </div>  
                </div>  
                <div class="duplicate">
                    <form class="ajax redirect" action="" method="post">
                    {% csrf_token %}
                        <h2> Please Confirm Your Selection :</h2>
                        {% for field in form %}
                        <div class="selection">
                            <label for="{{field.id_for_label}}">{{field.label}}</label>
                            {{field}}
                            <span class="delete {% cycle 'date' 'breakfast' 'lunch' 'snack' 'dinner' %}">Delete Selection</span>
                        </div>
                        {% endfor %}
                        <div class="submit">
                            <p class="error_message"></p>
                            <button type="submit"> submit </button>
                        </div>
                    </form>
                </div> 
        </section>
    </section>
    <script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{% static 'js/script.js' %}"></script>

</body>
</html>

src/food_management/templates/planner/my_orders.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'images/icons/favicon.png' %}" type="image/x-icon">
    <title>{{title}}</title>
</head>
<body>

    {% include "web/includes/header.html" %}
    <section id="bookings">
    <section class="wrapper">
        <div class="count">
            {% if required_date %}
                {% if required_date|length > 1 %}
                <strong>my bookings : {{required_date|length}}  </strong> <span>orders available</span> 
                {% else %}
                <strong>my bookings : {{required_date|length}}  </strong> <span>order available</span>
                {% endif %}
            {% else %}
                <h3>ohh ! you didn't make any orders yet </h3>
                <a href="{% url 'planner:planner' %}" class="button">Click Here to Make an Order</a>
            {% endif %}
        </div>
        {% for bookings in  order %}
            {% if bookings.selected_date >= today %}
                <div class="orders {% cycle 'one' 'two' 'three' %}">
                        <h1> {{ bookings.selected_date}}</h1>
                        <div class="buttons">
                            <a class="danger action-button reload"
                            href="{% url 'planner:delete_order' id=bookings.id %}"
                            data-text="Are you sure want to delete your order. You can't undo this action." 
                            data-title="Confirm Delete!"
                            title="Delete!">
                                <img src="{% static 'images/icons/delete.svg' %}" alt="Delete" />
                            </a>
                            <a class="warning" title="Edit!" href="{% url 'planner:edit_order' id=bookings.id %}" >
                                <img src="{% static 'images/icons/pencil.svg' %}" alt="Edit" />
                            </a>
                        </div>
                </div>
            {% endif %}
        {% endfor %}
    </section>
    </section>
    <script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

src/food_management/templates/planner/planner.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'images/icons/favicon.png' %}" type="image/x-icon">
    <title>{{title}}</title>
</head>
<body>
    {% include "web/includes/header.html" %}
    <section id="plan">
        <section class="wrapper">
                <div class="top">
                    <div class="date">
                        <h1>{{ today|date:'l' }}</h1>
                        <h4>{{ today|date:'d F Y' }}</h4>
                    </div>
                    <input type="hidden" name="selected_date" id="selected_date_input">
                    <input type="hidden" name="selected_bf" id="selected_bf_input">
                    <input type="hidden" name="selected_lc" id="selected_lc_input">
                    <input type="hidden" name="selected_snacks" id="selected_sk_input">
                    <input type="hidden" name="selected_dr" id="selected_dr_input">
                    <div class="days">
                        <h2>choose a date to book the meals</h2>
                        <ul>
                            
                            
                            {% for day in next_7_days %}
                                
                            <li class="item {% if day in selected_date %}red{% endif %}">
                                {% if day in selected_date %}
                                    <span class="common-date" data-value="{{ day|date:'Y-m-d' }}">
                                        <span>{{ day|date:'D' }}</span>{{ day|date:'d' }}
                                        <h6>booked</h6>
                                    </span>
                                    
                                {% else %}
                                    <a href="#" data-value="{{ day|date:'Y-m-d' }}">
                                        <span>{{ day|date:'D' }}</span>{{ day|date:'d' }}
                                    </a>
                                {% endif %}                        
                            {% endfor %}
                            <!-- {% for day in selected_date %}
                                
                            <li class="item ">
                                <a href="#" class="" data-value="{{ day|date:'Y-m-d' }}" ><span>{{day|date:'D' }}</span>{{day|date:'d' }}</a>
                            </li>
                        {% endfor %} -->
                        </ul>
                    </div>
                </div>
                <div class="meals">   
                        <div class="item">
                            <div class="menu_head">
                                <h3>Breakfast</h3>
                            </div>
                            <div class="menu breakfast">
                                <ul>
                                    {% for meal in breakfast %}
                                        <li class="item">
                                            <span class="radio">
                                                <span class="label"></span>
                                            </span>
                                            <a href="#" data-value="{{ meal.dish_name }}" >{{ meal.dish_name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="item">
                            <div class="menu_head">
                                <h3>Lunch</h3>
                            </div>
                            <div class="menu lunch">
                                <ul>
                                    {% for meal in lunch %}
                                        <li class="item">
                                            <span class="radio">
                                                <span class="label"></span>
                                            </span>
                                            <a href="#" data-value="{{ meal.dish_name }}" >{{ meal.dish_name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="item">
                            <div class="menu_head">
                                <h3>Evening Snack</h3>
                            </div>
                            <div class="menu snack" >
                                <ul>
                                    {% for meal in snack %}
                                        <li class="item">
                                            <span class="radio">
                                                <span class="label"></span>
                                            </span>
                                            <a href="#" data-value="{{ meal.dish_name }}" >{{ meal.dish_name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>      
                        </div>
                        <div class="item">
                            <div class="menu_head">
                                <h3>Dinner</h3>
                            </div>
                            <div class="menu dinner">
                                <ul>
                                    {% for meal in dinner %}
                                        <li class="item">
                                            <span class="radio">
                                                <span class="label"></span>
                                            </span>
                                            <a href="#" data-value="{{ meal.dish_name }}" >{{ meal.dish_name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>     
                        </div>
                        <div class="ready">
                            <button href="" class="button">make Selection</button>
                            <p class="info">click make selection and scroll down to confirm your order..!</p>
                        </div>  
                </div>  
                <div class="duplicate">
                    <form class="ajax redirect" action="" method="post">
                    {% csrf_token %}
                        <h2> Please Confirm Your Selection :</h2>
                        {% for field in form %}
                        <div class="selection">
                            <label for="{{field.id_for_label}}">{{field.label}}</label>
                            {{field}}
                            <span class="delete {% cycle 'date' 'breakfast' 'lunch' 'snack' 'dinner' %}">Delete Selection</span>
                        </div>
                        {% endfor %}
                        <div class="submit">
                            <p class="error_message"></p>
                            <button type="submit"> submit </button>
                        </div>
                    </form>
                </div> 
        </section>
    </section>
    <script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{% static 'js/script.js' %}"></script>

</body>
</html>